version: '3'
services:
    app:
        build: .
        links:
            - db
        volumes:
            - .:/var/wwwi
        ports:
            - "8000:8000"
        depends_on:
            - db
    db:
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USRE=test_user
            - MYSQL_DATABASE=cloud_note
            - MYSQL_PASSWORD=test_pass
volumes:
    db_data:
